import type { Metadata } from "next";
import "./globals.css";
import "remixicon/fonts/remixicon.css";

import ClientLayout from "@/components/clientLayout/clientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientLayout>{children}</ClientLayout>
    </html>
  );
}
